import React, { useState } from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { Landing } from './components/Landing';
import { Auth } from './components/Auth';
import { KeyboardApp } from './components/KeyboardApp';
import { X } from 'lucide-react';

const App: React.FC = () => {
  const [isMinimized, setIsMinimized] = useState(false);

  const Logo = () => (
    <svg viewBox="0 0 100 100" className="w-6 h-6 rounded-md shadow-sm" xmlns="http://www.w3.org/2000/svg">
      <rect width="100" height="100" fill="black" />
      <rect x="41" y="19" width="18" height="18" fill="white" />
      <rect x="19" y="41" width="18" height="18" fill="white" />
      <rect x="41" y="41" width="18" height="18" fill="white" />
      <rect x="63" y="41" width="18" height="18" fill="white" />
      <rect x="41" y="63" width="18" height="18" fill="white" />
    </svg>
  );

  return (
    <BrowserRouter>
      <div className="relative min-h-screen pb-20">
        <Routes>
          <Route path="/" element={<Landing />} />
          <Route path="/auth" element={<Auth />} />
          <Route path="/app" element={<KeyboardApp />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>

        {/* Vdev Badge */}
        {!isMinimized ? (
          <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[100]">
            <div className="group relative flex items-center justify-center">
              <div className="bg-white/90 backdrop-blur-sm border border-zinc-200 shadow-lg rounded-2xl pl-5 pr-2 py-2 text-sm font-medium text-zinc-600 transition-all duration-500 ease-out hover:shadow-xl hover:border-zinc-300 hover:-translate-y-0.5 flex items-center gap-3">
                <div className="flex items-center gap-2.5 cursor-default">
                  <span className="font-serif italic text-base">Generated with</span>
                  <Logo />
                </div>
                
                <div className="w-px h-4 bg-zinc-200"></div>
                
                <button
                  onClick={() => setIsMinimized(true)}
                  className="relative p-1.5 text-zinc-400 hover:text-zinc-900 transition-colors duration-500 ease-out rounded-full group/btn overflow-hidden"
                  aria-label="Minimize badge"
                >
                  <span className="absolute inset-0 bg-zinc-200 rounded-full scale-0 group-hover/btn:scale-100 transition-transform duration-500 ease-out origin-center"></span>
                  <X className="w-4 h-4 relative z-10" />
                </button>
              </div>
              
              {/* Tooltip */}
              <div className="absolute bottom-full mb-3 opacity-0 group-hover:opacity-100 transition-opacity duration-500 ease-out pointer-events-none w-max max-w-[280px] text-center">
                <div className="bg-zinc-900 text-white text-xs py-2 px-3 rounded-xl shadow-xl relative">
                  This was generated by vdev 1.2 Pro by opencry
                  <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-zinc-900 rotate-45"></div>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="fixed bottom-6 right-6 z-[100]">
            <div className="group relative flex items-center justify-center">
              <button 
                onClick={() => setIsMinimized(false)}
                className="bg-white/90 backdrop-blur-sm border border-zinc-200 shadow-lg rounded-xl p-2.5 text-zinc-600 transition-all duration-500 ease-out hover:shadow-xl hover:border-zinc-300 hover:-translate-y-0.5 flex items-center justify-center"
                aria-label="Expand badge"
              >
                <Logo />
              </button>
              
              {/* Tooltip */}
              <div className="absolute bottom-full right-0 mb-3 opacity-0 group-hover:opacity-100 transition-opacity duration-500 ease-out pointer-events-none w-max max-w-[280px] text-center">
                <div className="bg-zinc-900 text-white text-xs py-2 px-3 rounded-xl shadow-xl relative">
                  Show information
                  <div className="absolute -bottom-1 right-3 w-2 h-2 bg-zinc-900 rotate-45"></div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </BrowserRouter>
  );
};

export default App;